name: Create release with docker

on:
  push:
    tags: 
      - 'v*'
 
jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
          name: Create Relase
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
              Changes in this Release
              - First Change
              - Second Change
            draft: false
            prerelease: false
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        name: Build the Docker image
        run: docker buildx build --tag ghcr.io/mwinters-stuff/tuya-mqtt-docker:${{ github.ref }} --tag ghcr.io/mwinters-stuff/tuya-mqtt-docker:latest --push --platform=linux/arm64 --platform=linux/arm --platform=linux/amd64 .
